version: 0.2

phases:
  install:
    commands:
      - echo Installing dependencies...
      - mvn install -DskipTests=true
  build:
    commands:
      - echo Build started on `date`
      - mvn package
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Uploading artifact to S3...
      - aws s3 cp target/aws-0.0.1-SNAPSHOT.jar s3://elasticbeanstalk-ap-south-1-590183925729/aws-0.0.1-SNAPSHOT.jar

artifacts:
  files:
    - target/your-app.jar
